onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group config_avalon_stimuli -radix hexadecimal /testbench_top/config_avalon_stimuli_inst/clk_i
add wave -noupdate -group config_avalon_stimuli -radix hexadecimal /testbench_top/config_avalon_stimuli_inst/rst_i
add wave -noupdate -group config_avalon_stimuli -radix hexadecimal /testbench_top/config_avalon_stimuli_inst/avalon_mm_readdata_i
add wave -noupdate -group config_avalon_stimuli -radix hexadecimal /testbench_top/config_avalon_stimuli_inst/avalon_mm_waitrequest_i
add wave -noupdate -group config_avalon_stimuli -radix hexadecimal /testbench_top/config_avalon_stimuli_inst/avalon_mm_address_o
add wave -noupdate -group config_avalon_stimuli -radix hexadecimal /testbench_top/config_avalon_stimuli_inst/avalon_mm_write_o
add wave -noupdate -group config_avalon_stimuli -radix hexadecimal /testbench_top/config_avalon_stimuli_inst/avalon_mm_writedata_o
add wave -noupdate -group config_avalon_stimuli -radix hexadecimal /testbench_top/config_avalon_stimuli_inst/avalon_mm_read_o
add wave -noupdate -group config_avalon_stimuli -radix hexadecimal /testbench_top/config_avalon_stimuli_inst/s_counter
add wave -noupdate -group tb_avs_read -radix hexadecimal /testbench_top/dcom_tb_avs_read_ent_inst/clk_i
add wave -noupdate -group tb_avs_read -radix hexadecimal /testbench_top/dcom_tb_avs_read_ent_inst/rst_i
add wave -noupdate -group tb_avs_read -radix hexadecimal /testbench_top/dcom_tb_avs_read_ent_inst/dcom_tb_avs_avalon_mm_i
add wave -noupdate -group tb_avs_read -radix hexadecimal /testbench_top/dcom_tb_avs_read_ent_inst/dcom_tb_avs_avalon_mm_o
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/reset_sink_reset_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/sync_channel_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/clock_sink_100_clk_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/avalon_slave_dcom_address_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/avalon_slave_dcom_byteenable_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/avalon_slave_dcom_write_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/avalon_slave_dcom_read_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/avalon_slave_dcom_writedata_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/avalon_slave_dcom_readdata_o
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/avalon_slave_dcom_waitrequest_o
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/avalon_master_data_readdata_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/avalon_master_data_waitrequest_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/avalon_master_data_address_o
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/avalon_master_data_read_o
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/tx_interrupt_sender_irq_o
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_link_status_started_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_link_status_connecting_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_link_status_running_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_link_error_errdisc_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_link_error_errpar_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_link_error_erresc_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_link_error_errcred_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_timecode_rx_tick_out_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_timecode_rx_ctrl_out_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_timecode_rx_time_out_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_data_rx_status_rxvalid_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_data_rx_status_rxhalff_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_data_rx_status_rxflag_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_data_rx_status_rxdata_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_data_tx_status_txrdy_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_data_tx_status_txhalff_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_link_command_autostart_o
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_link_command_linkstart_o
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_link_command_linkdis_o
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_link_command_txdivcnt_o
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_timecode_tx_tick_in_o
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_timecode_tx_ctrl_in_o
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_timecode_tx_time_in_o
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_data_rx_command_rxread_o
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_data_tx_command_txwrite_o
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_data_tx_command_txflag_o
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/spw_data_tx_command_txdata_o
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/codec_rmap_wr_waitrequest_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/codec_rmap_readdata_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/codec_rmap_rd_waitrequest_i
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/codec_rmap_wr_address_o
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/codec_rmap_write_o
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/codec_rmap_writedata_o
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/codec_rmap_rd_address_o
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/codec_rmap_read_o
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/rmap_mem_addr_offset_o
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/rst_n
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_dcom_avalon_mm_read_waitrequest
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_dcom_avalon_mm_write_waitrequest
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_dcom_write_registers
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_dcom_read_registers
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_avm_data_master_rd_control
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_avm_data_master_rd_status
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_avs_dbuffer_wrdata
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_avs_dbuffer_wrreq
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_avs_dbuffer_halffull
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_avs_dbuffer_full
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_avs_bebuffer_wrdata
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_avs_bebuffer_wrreq
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_avs_bebuffer_halffull
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_avs_bebuffer_full
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_dcrtl_dbuffer_rddata
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_dcrtl_dbuffer_rdreq
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_dcrtl_dbuffer_empty
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_dctrl_tx_begin
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_dctrl_tx_ended
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_dctrl_spw_tx_ready
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_dctrl_spw_tx_write
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_dctrl_spw_tx_flag
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_dctrl_spw_tx_data
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_spw_codec_link_command_clk100
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_spw_codec_link_status_clk100
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_spw_codec_link_error_clk100
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_spw_codec_timecode_rx_clk100
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_spw_codec_data_rx_status_clk100
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_spw_codec_data_tx_status_clk100
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_spw_codec_timecode_tx_clk100
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_spw_codec_data_rx_command_clk100
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_spw_codec_data_tx_command_clk100
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_spw_codec_link_command_clk200
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_spw_codec_link_status_clk200
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_spw_codec_link_error_clk200
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_spw_codec_timecode_rx_clk200
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_spw_codec_data_rx_status_clk200
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_spw_codec_data_tx_status_clk200
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_spw_codec_timecode_tx_clk200
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_spw_codec_data_rx_command_clk200
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_spw_codec_data_tx_command_clk200
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_rxtc_tick_out
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_txirq_tx_begin_delayed
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_txirq_tx_ended_delayed
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_sync_in_trigger
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_sync_in_delayed
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_sync_channel_i_n
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_spw_dummy_rxvalid
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_spw_dummy_rxread
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_mux_rx_channel_command
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_mux_rx_channel_status
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_mux_tx_channel_command
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_mux_tx_channel_status
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_mux_tx_1_command
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_mux_tx_1_status
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_mux_tx_2_command
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_mux_tx_2_status
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_dummy_spw_mux_rx0_rxhalff
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_dummy_spw_mux_tx0_txhalff
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_rmap_spw_control
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_rmap_spw_flag
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_rmap_mem_control
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_rmap_mem_flag
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_rmap_mem_wr_byte_address
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/s_rmap_mem_rd_byte_address
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/a_reset
add wave -noupdate -group dcom_v2_top -radix hexadecimal /testbench_top/dcom_v2_top_inst/a_avs_clock
add wave -noupdate -group avm_data_reader -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_data_reader_ent_inst/clk_i
add wave -noupdate -group avm_data_reader -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_data_reader_ent_inst/rst_i
add wave -noupdate -group avm_data_reader -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_data_reader_ent_inst/avm_master_rd_control_i
add wave -noupdate -group avm_data_reader -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_data_reader_ent_inst/avm_slave_rd_status_i
add wave -noupdate -group avm_data_reader -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_data_reader_ent_inst/avm_master_rd_status_o
add wave -noupdate -group avm_data_reader -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_data_reader_ent_inst/avm_slave_rd_control_o
add wave -noupdate -group avm_data_reader -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_data_reader_ent_inst/s_avm_slave_rd_registered_control
add wave -noupdate -group avm_data_reader -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_data_reader_ent_inst/s_dcom_avm_data_reader_state
add wave -noupdate -group avm_reader_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_reader_controller_ent_inst/clk_i
add wave -noupdate -group avm_reader_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_reader_controller_ent_inst/rst_i
add wave -noupdate -group avm_reader_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_reader_controller_ent_inst/tmr_stop_i
add wave -noupdate -group avm_reader_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_reader_controller_ent_inst/tmr_start_i
add wave -noupdate -group avm_reader_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_reader_controller_ent_inst/controller_rd_start_i
add wave -noupdate -group avm_reader_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_reader_controller_ent_inst/controller_rd_reset_i
add wave -noupdate -group avm_reader_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_reader_controller_ent_inst/controller_rd_auto_restart_i
add wave -noupdate -group avm_reader_controller -radix unsigned /testbench_top/dcom_v2_top_inst/dcom_avm_reader_controller_ent_inst/controller_rd_initial_addr_i
add wave -noupdate -group avm_reader_controller -radix unsigned /testbench_top/dcom_v2_top_inst/dcom_avm_reader_controller_ent_inst/controller_rd_length_bytes_i
add wave -noupdate -group avm_reader_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_reader_controller_ent_inst/controller_wr_busy_i
add wave -noupdate -group avm_reader_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_reader_controller_ent_inst/avm_master_rd_status_i
add wave -noupdate -group avm_reader_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_reader_controller_ent_inst/data_buffer_full_i
add wave -noupdate -group avm_reader_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_reader_controller_ent_inst/be_buffer_full_i
add wave -noupdate -group avm_reader_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_reader_controller_ent_inst/controller_rd_busy_o
add wave -noupdate -group avm_reader_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_reader_controller_ent_inst/avm_master_rd_control_o
add wave -noupdate -group avm_reader_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_reader_controller_ent_inst/data_buffer_wrdata_o
add wave -noupdate -group avm_reader_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_reader_controller_ent_inst/data_buffer_wrreq_o
add wave -noupdate -group avm_reader_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_reader_controller_ent_inst/be_buffer_wrdata_o
add wave -noupdate -group avm_reader_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_reader_controller_ent_inst/be_buffer_wrreq_o
add wave -noupdate -group avm_reader_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_reader_controller_ent_inst/s_dcom_avm_reader_controller_state
add wave -noupdate -group avm_reader_controller -radix unsigned /testbench_top/dcom_v2_top_inst/dcom_avm_reader_controller_ent_inst/s_rd_addr_cnt
add wave -noupdate -group avm_reader_controller -radix unsigned /testbench_top/dcom_v2_top_inst/dcom_avm_reader_controller_ent_inst/s_rd_data_cnt
add wave -noupdate -group avm_reader_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/dcom_avm_reader_controller_ent_inst/s_auto_restart
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/clk_i
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/rst_i
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/tmr_clear_i
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/tmr_stop_i
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/tmr_start_i
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/avs_dbuffer_wrdata_i
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/avs_dbuffer_wrreq_i
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/avs_bebuffer_wrdata_i
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/avs_bebuffer_wrreq_i
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/dcrtl_dbuffer_rdreq_i
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/dbuff_empty_o
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/dbuff_full_o
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/dbuff_usedw_o
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/avs_dbuffer_halffull_o
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/avs_dbuffer_full_o
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/avs_bebuffer_halffull_o
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/avs_bebuffer_full_o
add wave -noupdate -group data_buffer -radix hexadecimal -childformat {{/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/dcrtl_dbuffer_rddata_o(7) -radix hexadecimal} {/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/dcrtl_dbuffer_rddata_o(6) -radix hexadecimal} {/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/dcrtl_dbuffer_rddata_o(5) -radix hexadecimal} {/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/dcrtl_dbuffer_rddata_o(4) -radix hexadecimal} {/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/dcrtl_dbuffer_rddata_o(3) -radix hexadecimal} {/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/dcrtl_dbuffer_rddata_o(2) -radix hexadecimal} {/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/dcrtl_dbuffer_rddata_o(1) -radix hexadecimal} {/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/dcrtl_dbuffer_rddata_o(0) -radix hexadecimal}} -subitemconfig {/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/dcrtl_dbuffer_rddata_o(7) {-height 15 -radix hexadecimal} /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/dcrtl_dbuffer_rddata_o(6) {-height 15 -radix hexadecimal} /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/dcrtl_dbuffer_rddata_o(5) {-height 15 -radix hexadecimal} /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/dcrtl_dbuffer_rddata_o(4) {-height 15 -radix hexadecimal} /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/dcrtl_dbuffer_rddata_o(3) {-height 15 -radix hexadecimal} /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/dcrtl_dbuffer_rddata_o(2) {-height 15 -radix hexadecimal} /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/dcrtl_dbuffer_rddata_o(1) {-height 15 -radix hexadecimal} /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/dcrtl_dbuffer_rddata_o(0) {-height 15 -radix hexadecimal}} /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/dcrtl_dbuffer_rddata_o
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/dcrtl_dbuffer_empty_o
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_dbuffer_fifo
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_dbuffer_sclr
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_bebuffer_fifo
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_bebuffer_sclr
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_dctrl_dbuffer_fifo
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_dctrl_dbuffer_sclr
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_data_buffer_state
add wave -noupdate -group data_buffer -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_byte_counter
add wave -noupdate -group data_buffer -radix hexadecimal -childformat {{/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_dbuffer_data_bytes(0) -radix hexadecimal} {/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_dbuffer_data_bytes(1) -radix hexadecimal} {/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_dbuffer_data_bytes(2) -radix hexadecimal} {/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_dbuffer_data_bytes(3) -radix hexadecimal} {/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_dbuffer_data_bytes(4) -radix hexadecimal} {/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_dbuffer_data_bytes(5) -radix hexadecimal} {/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_dbuffer_data_bytes(6) -radix hexadecimal} {/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_dbuffer_data_bytes(7) -radix hexadecimal}} -subitemconfig {/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_dbuffer_data_bytes(0) {-height 15 -radix hexadecimal} /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_dbuffer_data_bytes(1) {-height 15 -radix hexadecimal} /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_dbuffer_data_bytes(2) {-height 15 -radix hexadecimal} /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_dbuffer_data_bytes(3) {-height 15 -radix hexadecimal} /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_dbuffer_data_bytes(4) {-height 15 -radix hexadecimal} /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_dbuffer_data_bytes(5) {-height 15 -radix hexadecimal} /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_dbuffer_data_bytes(6) {-height 15 -radix hexadecimal} /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_dbuffer_data_bytes(7) {-height 15 -radix hexadecimal}} /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_dbuffer_data_bytes
add wave -noupdate -group data_buffer -radix hexadecimal -childformat {{/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_bebuffer_data_bits(0) -radix hexadecimal} {/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_bebuffer_data_bits(1) -radix hexadecimal} {/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_bebuffer_data_bits(2) -radix hexadecimal} {/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_bebuffer_data_bits(3) -radix hexadecimal} {/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_bebuffer_data_bits(4) -radix hexadecimal} {/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_bebuffer_data_bits(5) -radix hexadecimal} {/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_bebuffer_data_bits(6) -radix hexadecimal} {/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_bebuffer_data_bits(7) -radix hexadecimal}} -subitemconfig {/testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_bebuffer_data_bits(0) {-height 15 -radix hexadecimal} /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_bebuffer_data_bits(1) {-height 15 -radix hexadecimal} /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_bebuffer_data_bits(2) {-height 15 -radix hexadecimal} /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_bebuffer_data_bits(3) {-height 15 -radix hexadecimal} /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_bebuffer_data_bits(4) {-height 15 -radix hexadecimal} /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_bebuffer_data_bits(5) {-height 15 -radix hexadecimal} /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_bebuffer_data_bits(6) {-height 15 -radix hexadecimal} /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_bebuffer_data_bits(7) {-height 15 -radix hexadecimal}} /testbench_top/dcom_v2_top_inst/data_buffer_ent_inst/s_avs_bebuffer_data_bits
add wave -noupdate -group data_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/clk_i
add wave -noupdate -group data_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/rst_i
add wave -noupdate -group data_controller -radix unsigned /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/tmr_time_i
add wave -noupdate -group data_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/tmr_stop_i
add wave -noupdate -group data_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/tmr_start_i
add wave -noupdate -group data_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/dctrl_send_eep_i
add wave -noupdate -group data_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/dctrl_send_eop_i
add wave -noupdate -group data_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/dbuffer_empty_i
add wave -noupdate -group data_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/dbuffer_rddata_i
add wave -noupdate -group data_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/spw_tx_ready_i
add wave -noupdate -group data_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/dctrl_tx_begin_o
add wave -noupdate -group data_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/dctrl_tx_ended_o
add wave -noupdate -group data_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/dbuffer_rdreq_o
add wave -noupdate -group data_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/spw_tx_write_o
add wave -noupdate -group data_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/spw_tx_flag_o
add wave -noupdate -group data_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/spw_tx_data_o
add wave -noupdate -group data_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/s_data_controller_state
add wave -noupdate -group data_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/s_data_controller_return_state
add wave -noupdate -group data_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/s_word_counter
add wave -noupdate -group data_controller -radix unsigned /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/s_data_packet_length
add wave -noupdate -group data_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/s_data_packet_length_words
add wave -noupdate -group data_controller -radix unsigned /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/s_data_packet_time
add wave -noupdate -group data_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/s_data_packet_time_words
add wave -noupdate -group data_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/s_spw_transmitting
add wave -noupdate -group data_controller -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_controller_ent_inst/s_alignment_counter
add wave -noupdate -group data_scheduler -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_scheduler_ent_inst/clk_i
add wave -noupdate -group data_scheduler -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_scheduler_ent_inst/rst_i
add wave -noupdate -group data_scheduler -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_scheduler_ent_inst/tmr_run_on_sync_i
add wave -noupdate -group data_scheduler -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_scheduler_ent_inst/tmr_clk_div_i
add wave -noupdate -group data_scheduler -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_scheduler_ent_inst/tmr_time_in_i
add wave -noupdate -group data_scheduler -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_scheduler_ent_inst/tmr_clear_i
add wave -noupdate -group data_scheduler -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_scheduler_ent_inst/tmr_stop_i
add wave -noupdate -group data_scheduler -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_scheduler_ent_inst/tmr_run_i
add wave -noupdate -group data_scheduler -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_scheduler_ent_inst/tmr_start_i
add wave -noupdate -group data_scheduler -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_scheduler_ent_inst/sync_i
add wave -noupdate -group data_scheduler -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_scheduler_ent_inst/tmr_cleared_o
add wave -noupdate -group data_scheduler -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_scheduler_ent_inst/tmr_running_o
add wave -noupdate -group data_scheduler -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_scheduler_ent_inst/tmr_started_o
add wave -noupdate -group data_scheduler -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_scheduler_ent_inst/tmr_stopped_o
add wave -noupdate -group data_scheduler -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_scheduler_ent_inst/tmr_time_out_o
add wave -noupdate -group data_scheduler -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_scheduler_ent_inst/s_data_scheduler_state
add wave -noupdate -group data_scheduler -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_scheduler_ent_inst/s_tmr_time
add wave -noupdate -group data_scheduler -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_scheduler_ent_inst/s_tmr_registered_clkdiv
add wave -noupdate -group data_scheduler -radix hexadecimal /testbench_top/dcom_v2_top_inst/data_scheduler_ent_inst/s_tmr_evt_counter
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {50075000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 251
configure wave -valuecolwidth 158
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {300 ns} {126300 ns}
