#!/bin/sh
#
# This file was automatically generated by the Nios II IDE Flash Programmer.
#
# It will be overwritten when the flash programmer options change.
#
"$SOPC_KIT_NIOS2/nios2_command_shell.sh" perl program_flash.pl